-- AlterTable
ALTER TABLE `report` MODIFY `reportType` ENUM('MONTHLY', 'QUARTERLY', 'ANNUAL', 'EMERGENCY', 'INCIDENT', 'VACCINATION_CAMPAIGN', 'DISEASE_OUTBREAK', 'PHARMACEUTICAL', 'OTHER') NOT NULL;
